#!/bin/bash
run_id="${1}"

DDBJ_API_EP="http://13.231.66.138/api/sra/accession"

get_ncbi_url(){
  local id=${1}
  local base="ftp://ftp.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra"
  local url="${base}/${id:0:3}/${id:0:6}/${id}/${id}.sra"
  echo ${url}
}

get_ebi_url(){
  local id=${1}
  local base="ftp://ftp.sra.ebi.ac.uk/vol1"
  local pdir="${base}/$(echo ${id:0:3} | tr [:upper:] [:lower:])/${id:0:6}"
  if test $(printf ${id} | wc -c) -eq 10; then
    local url="${pdir}/00${id: -1}/${id}"
  else
    local url="${pdir}/${id}"
  fi
  echo ${url}
}

get_ddbj_url(){
  local id=${1}
  local base="ftp://ftp.ddbj.nig.ac.jp/ddbj_database/dra/sralite/ByExp/litesra"
  local expid=$(curl ${DDBJ_API_EP}/${id} | jq -r .Experiment)
  local url="${base}/${expid:0:3}/${expid:0:6}/${expid}/${id}/${id}.sra"
  echo ${url}
}

case ${2} in
  "ncbi" | "NCBI" )
    data_url="$(get_ncbi_url ${run_id})"
    ;;
  "ebi" | "EBI" )
    data_url="$(get_ebi_url ${run_id})"
    ;;
  "ddbj" | "DDBJ" )
    data_url="$(get_ddbj_url ${run_id})"
    ;;
  *)
    data_url="$(get_ncbi_url ${run_id})"
    ;;
esac

if [[ ! -z ${run_id} ]]; then
  wget -O "$(pwd)/${run_id}.sra" ${data_url}
else
  echo "usage: download_sra <SRA Run ID> [ncbi|ebi|ddbj]"
  exit 1
fi
