#!/bin/sh

get_ebi_url(){
  local id=${1}
  local base="ftp://ftp.sra.ebi.ac.uk/vol1"
  local pdir="${base}/$(echo ${id:0:3} | tr [:upper:] [:lower:])/${id:0:6}"
  if test $(printf ${id} | wc -c) -eq 10; then
    local url="${pdir}/00${id: -1}/${id}"
  elif test $(printf ${id} | wc -c) -eq 11; then
    local url="${pdir}/0${id: -2}/${id}"
  else
    local url="${pdir}/${id}"
  fi
  echo ${url}
}

get_experiment_from_run() {
  local id=${1}
  local api_url="https://api.togoid.dbcls.jp/convert?format=tsv&report=target&route=sra_run,sra_experiment&ids=${id}"
  curl ${api_url} | tail -n 1
}

get_ddbj_url(){
  local id=${1}
  local expid="$(get_experiment_from_run "${id}")"
  local url="ftp://ftp.ddbj.nig.ac.jp/ddbj_database/dra/sralite/ByExp/litesra/${expid:0:3}/${expid:0:6}/${expid}/${id}/${id}.sra"
  echo ${url}
}

download_from_ncbi() {
  local run_id=${1}
  prefetch "${run_id}"
}

download_from_ebi() {
  local run_id=${1}
  curl -s --output "${run_id}.sra" "$(get_ebi_url ${run_id})"
}

download_from_ddbj() {
  local run_id=${1}
  curl -s --output "${run_id}.sra" "$(get_ddbj_url ${run_id})"
}

if test $# -eq 0; then
  echo "usage: download_sra [-r|--repo] [ncbi|ebi|ddbj] <SRA Run ID>[ <Run ID>..]"
  exit 1
else
  while test $# -gt 0; do
    key=${1}
    case ${key} in
      "-r" | "--repo" | "--repository" )
        REPO=${2}
        shift
        ;;
      "-v" )
        set -x
        ;;
      ?RR[0-9]* )
        RUN_ID="${key} ${RUN_ID}"
        ;;
    esac
    shift
  done
fi

for run_id in ${RUN_ID}; do
  case ${REPO} in
    "ncbi" | "NCBI" )
      download_from_ncbi "${run_id}"
      ;;
    "ebi" | "EBI" )
      download_from_ebi "${run_id}"
      ;;
    "ddbj" | "DDBJ" )
      download_from_ddbj "${run_id}"
      ;;
    *)
      download_from_ddbj "${run_id}"
      ;;
  esac
done
