#!/bin/sh
run_id="${1}"

get_ncbi_url(){
  local id=${1}
  local base="ftp://ftp.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra"
  local url="${base}/${id:0:3}/${id:0:6}/${id}/${id}.sra"
  echo ${url}
}

get_ebi_url(){
  local id=${1}
  local base="ftp://ftp.sra.ebi.ac.uk/vol1"
  local pdir="${base}/$(echo ${id:0:3} | tr [:upper:] [:lower:])/${id:0:6}"
  if test $(printf ${id} | wc -c) -eq 10; then
    local url="${pdir}/00${id: -1}/${id}"
  elif test $(printf ${id} | wc -c) -eq 11; then
    local url="${pdir}/0${id: -2}/${id}"
  else
    local url="${pdir}/${id}"
  fi
  echo ${url}
}

get_ddbj_url(){
  local id=${1}
  local urlbase="ftp://ftp.ddbj.nig.ac.jp"
  local sralist="${urlbase}/ddbj_database/dra/meta/list/sralist"
  cd "/tmp" && wget -N ${sralist}
  local url=$(awk '/'"${id}"'.sra/ { print $1 }' $(basename ${sralist}) | head -1)
  echo "${urlbase}/${url}"
}

if test $# -eq 0; then
  echo "usage: download_sra [-r|--repo] [ncbi|ebi|ddbj] <SRA Run ID>[ <Run ID>..]"
  exit 1
else
  while test $# -gt 0; do
    key=${1}
    case ${key} in
      "-r" | "--repo" | "--repository" )
        REPO=${2}
        shift
        ;;
      ?RR[0-9]* )
        RUN_ID="${key} ${RUN_ID}"
        ;;
    esac
    shift
  done
fi

for run_id in ${RUN_ID}; do
  case ${REPO} in
    "ncbi" | "NCBI" )
      data_url="$(get_ncbi_url ${run_id})"
      ;;
    "ebi" | "EBI" )
      data_url="$(get_ebi_url ${run_id})"
      ;;
    "ddbj" | "DDBJ" )
      data_url="$(get_ddbj_url ${run_id})"
      ;;
    *)
      data_url="$(get_ncbi_url ${run_id})"
      ;;
  esac

  wget -O "${run_id}.sra" ${data_url}
done
